---
- name: Deploy Latest Version of Portfolio
  hosts: portfolio_container
  become: true

  tasks:
    - name: Get Latest Version of Portfolio
      ansible.builtin.git:
        repo: 'git@github.com:JonathanWindell/PersonalPortfolio.git'
        dest: /opt/docker-projects/portfolio-site/code
        version: main
        key_file: /home/ubuntu/.ssh/id_ed25519 # Change to Correct Search Path
        accept_hostkey: yes
        force: yes

    - name: Restart Docker Container
      ansible.builtin.command:
        chdir: /opt/docker-projects/portfolio-site/code
        cmd: docker compose up -d --force-recreate