[docker_server_1]
docker-srv-01 

[n8n:children]
docker_server_1

[portfolio:children]
docker_server_1

[paperless:children]
docker_server_1

[docker_server_2]
torrent-srv

[torrent:children]
docker_server_2